server:
    port: 8081
    address: localhost

spring:
    profiles: prod

    thymeleaf:
        mode: XHTML
        cache: true

mongodb:
    url: localhost:27017
    databaseName: agate
    username:
    password:

shiro:
  password:
    nbHashIterations: 10000
    salt: agate

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600